# application.yml (common config as per environment )
#Author - Dheeraj Sharma
# mvn spring-boot:run -Dspring-boot.run.profiles=dev
spring:
  application:
    name: helix-health-platform
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
